export const STORAGE_KEYS = {
    BEST_SCORE: 'bestLocalScore',
    GAME_STATE: 'paperclipFactorySave',
};

export const GAME_CONFIG = {
    INITIAL_WIRE: 1000,
    INITIAL_WIRE_COST: 20,
    INITIAL_PRICE: 0.25,
    INITIAL_DEMAND: 50,
    INITIAL_AUTO_CLIPPER_COST: 5,
    AUTO_CLIPPER_COST_MULTIPLIER: 1.15,
    WIRE_PURCHASE_AMOUNT: 1000,

    INITIAL_MAX_CLIPS: 5000,
    INITIAL_WAREHOUSE_COST: 100,
    WAREHOUSE_EXPANSION_AMOUNT: 5000,
    WAREHOUSE_COST_MULTIPLIER: 1.5,

    INITIAL_MAX_CLIPPERS: 100,
    INITIAL_EXPANSION_COST: 2000,
    EXPANSION_AMOUNT: 100,
    EXPANSION_COST_MULTIPLIER: 2,

    INSURANCE_BASE_COST: 1000,
    INSURANCE_DURATION_MS: 5 * 60 * 1000,

    EFFICIENCY_BASE_COST: 1000,
    EFFICIENCY_INCREMENT: 0.5,

    MARKETING_BASE_COST: 100,
    MARKETING_DEMAND_BONUS: 20,
    DEMAND_CAP_PER_LEVEL: 100,

    EVENT_CHECK_INTERVAL_MS: 3000,
    EVENT_BASE_CHANCE: 0.10,
    EVENT_SUB_CHANCE: 0.25,
    THEFT_AMOUNT: 500,
    FIRE_CLIP_LOSS: 500,
    CLIPPER_LOSS: 20,
    MONEY_THRESHOLD_FOR_THEFT: 4500,
    CLIPS_THRESHOLD_FOR_FIRE: 7500,
    CLIPPERS_THRESHOLD_FOR_DAMAGE: 100,
    DEMAND_THRESHOLD_FOR_NEGATIVE_PR: 100,

    PRODUCTION_TICK_MS: 1000,
    SELL_TICK_MS: 2000,

    AUTO_SAVE_INTERVAL_MS: 30000,
    OFFLINE_PROGRESS_CAP_MS: 8 * 60 * 60 * 1000,

    RECORD_THRESHOLD: 1000,

    TROPHY_BRONZE_THRESHOLD: 1000,
    TROPHY_SILVER_THRESHOLD: 10000,
    TROPHY_GOLD_THRESHOLD: 100000,

    PRICE_ADJUST_INTERVAL_MS: 180,
    PRICE_ADJUST_DELTA: 0.01,
    MIN_PRICE: 0.01,
};
