// Caching strategy:
//  - Code & markup (html/css/js/manifest): stale-while-revalidate — served
//    instantly from cache, refreshed in the background, so deployed updates
//    reach returning players on their NEXT visit without manual cache bumps.
//  - Media under assets/ (audio, images, fonts): cache-first — immutable in
//    practice.
// The precache list and cache version below are generated from the actual
// files on disk; CI fails if they drift.
//
// Activation is deliberately NOT immediate. `skipWaiting()` used to run on
// install, so a new worker took over — and deleted the old cache — while an
// open tab was still running the previous build's HTML. Any module that tab
// requested afterwards came back from the new build: two versions of the game
// in one page. The new worker now waits until every tab is gone, or until the
// page explicitly asks it to take over via a SKIP_WAITING message, which the
// page only sends after telling the player to reload.

// AUTOGEN:START — generated by tools/generate-sw-assets.mjs (npm run build-sw); do not edit.
const CACHE_VERSION = '57255f87';
const ASSETS = [
    './',
    './assets/audio/Trophy.mp3',
    './assets/audio/buy.mp3',
    './assets/audio/cash.mp3',
    './assets/audio/click.mp3',
    './assets/audio/completion.mp3',
    './assets/audio/fail.mp3',
    './assets/audio/fire.mp3',
    './assets/audio/warning.mp3',
    './assets/fonts/LICENSE.txt',
    './assets/fonts/noto-kufi-arabic-subset.woff2',
    './assets/images/background.webp',
    './assets/images/icon-192.png',
    './assets/images/icon-512.png',
    './assets/images/trophy-bronze-64.webp',
    './assets/images/trophy-gold-64.webp',
    './assets/images/trophy-silver-64.webp',
    './css/styles.css',
    './index.html',
    './js/achievements.js',
    './js/audio.js',
    './js/clock.js',
    './js/config.js',
    './js/economy.js',
    './js/effects.js',
    './js/events.js',
    './js/feedback.js',
    './js/format.js',
    './js/game-loop.js',
    './js/input.js',
    './js/main.js',
    './js/offline.js',
    './js/onboarding.js',
    './js/prestige.js',
    './js/production.js',
    './js/save-ui.js',
    './js/save.js',
    './js/settings.js',
    './js/state.js',
    './js/ui.js',
    './js/upgrades.js',
    './manifest.json',
];
// AUTOGEN:END

const CACHE_NAME = `paperclip-factory-${CACHE_VERSION}`;

// The app shell must be complete for the game to boot offline; media can be
// fetched on demand. Splitting them means one failed audio file no longer
// fails the whole install and leaves the player with no offline mode at all.
const isMedia = (path) => path.includes('/assets/');
const SHELL_ASSETS = ASSETS.filter((path) => !isMedia(path));
const MEDIA_ASSETS = ASSETS.filter(isMedia);

async function precache() {
    const cache = await caches.open(CACHE_NAME);
    // Required: a rejection here fails the install, which is what we want.
    await cache.addAll(SHELL_ASSETS);
    // Best effort: warm what we can, ignore what we cannot.
    await Promise.allSettled(MEDIA_ASSETS.map((path) => cache.add(path)));
}

self.addEventListener('install', (event) => {
    event.waitUntil(precache());
});

// The page sends this once the player has been told an update is ready.
self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('activate', (event) => {
    event.waitUntil(
        caches.keys().then((keys) =>
            Promise.all(
                keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key)),
            ),
        ),
    );
    self.clients.claim();
});

async function cacheFirst(request) {
    const cached = await caches.match(request);
    if (cached) return cached;
    const response = await fetch(request);
    if (response && response.status === 200) {
        const cache = await caches.open(CACHE_NAME);
        cache.put(request, response.clone());
    }
    return response;
}

async function staleWhileRevalidate(request) {
    const cache = await caches.open(CACHE_NAME);
    const cached = await cache.match(request);
    const network = fetch(request)
        .then((response) => {
            if (response && response.status === 200) {
                cache.put(request, response.clone());
            }
            return response;
        })
        .catch(() => null);
    if (cached) return cached;
    const response = await network;
    if (response) return response;
    // Offline miss: only navigations may fall back to the app shell — code
    // and data requests must fail loudly rather than receive HTML.
    if (request.mode === 'navigate') {
        const shell = await caches.match('./index.html');
        if (shell) return shell;
    }
    return Response.error();
}

self.addEventListener('fetch', (event) => {
    const { request } = event;
    if (request.method !== 'GET') return;
    const url = new URL(request.url);
    if (url.origin !== self.location.origin) return;
    event.respondWith(isMedia(url.pathname) ? cacheFirst(request) : staleWhileRevalidate(request));
});
