// Caching strategy:
//  - Code & markup (html/css/js/manifest): stale-while-revalidate — served
//    instantly from cache, refreshed in the background, so deployed updates
//    reach returning players on their NEXT visit without manual cache bumps.
//  - Media under assets/ (audio, images): cache-first — immutable in practice.
// The precache list and cache version below are generated from the actual
// files on disk; CI fails if they drift.

// AUTOGEN:START — generated by tools/generate-sw-assets.mjs (npm run build-sw); do not edit.
const CACHE_VERSION = '251a41f7';
const ASSETS = [
    './',
    './assets/audio/Trophy.mp3',
    './assets/audio/buy.mp3',
    './assets/audio/cash.mp3',
    './assets/audio/click.mp3',
    './assets/audio/completion.mp3',
    './assets/audio/fail.mp3',
    './assets/audio/fire.mp3',
    './assets/audio/warning.mp3',
    './assets/images/background.webp',
    './assets/images/icon-192.png',
    './assets/images/icon-512.png',
    './assets/images/trophy-bronze-64.webp',
    './assets/images/trophy-gold-64.webp',
    './assets/images/trophy-silver-64.webp',
    './css/styles.css',
    './index.html',
    './js/achievements.js',
    './js/audio.js',
    './js/config.js',
    './js/effects.js',
    './js/events.js',
    './js/format.js',
    './js/game-loop.js',
    './js/main.js',
    './js/production.js',
    './js/save.js',
    './js/state.js',
    './js/ui.js',
    './js/upgrades.js',
    './manifest.json',
];
// AUTOGEN:END

const CACHE_NAME = `paperclip-factory-${CACHE_VERSION}`;

self.addEventListener('install', (event) => {
    event.waitUntil(
        caches.open(CACHE_NAME).then((cache) => cache.addAll(ASSETS)),
    );
    self.skipWaiting();
});

self.addEventListener('activate', (event) => {
    event.waitUntil(
        caches.keys().then((keys) =>
            Promise.all(
                keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key)),
            ),
        ),
    );
    self.clients.claim();
});

async function cacheFirst(request) {
    const cached = await caches.match(request);
    if (cached) return cached;
    const response = await fetch(request);
    if (response && response.status === 200) {
        const cache = await caches.open(CACHE_NAME);
        cache.put(request, response.clone());
    }
    return response;
}

async function staleWhileRevalidate(request) {
    const cache = await caches.open(CACHE_NAME);
    const cached = await cache.match(request);
    const network = fetch(request)
        .then((response) => {
            if (response && response.status === 200) {
                cache.put(request, response.clone());
            }
            return response;
        })
        .catch(() => null);
    if (cached) return cached;
    const response = await network;
    if (response) return response;
    // Offline miss: only navigations may fall back to the app shell — code
    // and data requests must fail loudly rather than receive HTML.
    if (request.mode === 'navigate') {
        const shell = await caches.match('./index.html');
        if (shell) return shell;
    }
    return Response.error();
}

self.addEventListener('fetch', (event) => {
    const { request } = event;
    if (request.method !== 'GET') return;
    const url = new URL(request.url);
    if (url.origin !== self.location.origin) return;
    const isMedia = url.pathname.includes('/assets/');
    event.respondWith(isMedia ? cacheFirst(request) : staleWhileRevalidate(request));
});
